# Generated by Django 5.2 on 2025-09-22 11:34

from django.conf import settings
from django.db import migrations, models


def assign_users_to_purchases(apps, schema_editor):
    Purchase = apps.get_model("core", "Purchase")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    default_user = User.objects.order_by("id").first()
    if default_user is None:
        default_user, _ = User.objects.get_or_create(username="purchase_placeholder_user")

    Purchase.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_walletuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_users_to_purchases, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
